# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongomapper-search}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Fernando Meyer"]
  s.date = %q{2009-12-07}
  s.description = %q{Easily integreate mongo mapper with enterprise search like solr}
  s.email = %q{fmcamargo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/mongomapper-search.rb",
     "lib/solr/search.rb",
     "spec/solr/search_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/fmeyer/mongomapper-search}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easily integreate mongo mapper with enterprise search like solr}
  s.test_files = [
    "spec/solr/search_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<rsolr>, ["= 0.9.6"])
      s.add_runtime_dependency(%q<mongo_mapper>, ["= 0.5.8"])
      s.add_runtime_dependency(%q<will_paginate>, ["= 2.3.11"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<rsolr>, ["= 0.9.6"])
      s.add_dependency(%q<mongo_mapper>, ["= 0.5.8"])
      s.add_dependency(%q<will_paginate>, ["= 2.3.11"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<rsolr>, ["= 0.9.6"])
    s.add_dependency(%q<mongo_mapper>, ["= 0.5.8"])
    s.add_dependency(%q<will_paginate>, ["= 2.3.11"])
  end
end

